// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ou6I7NZG7qa74ILubN8r4elicbUkdIM',
    appId: '1:570476177146:web:05bcc0738c105748370b43',
    messagingSenderId: '570476177146',
    projectId: 'chat-app-last-try',
    authDomain: 'chat-app-last-try.firebaseapp.com',
    storageBucket: 'chat-app-last-try.appspot.com',
    measurementId: 'G-1BTLHY2CNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeUR8p3oe4wWgWXjtjSq7xIIrLNgMaA0',
    appId: '1:570476177146:android:0ccb65c74f4e8eff370b43',
    messagingSenderId: '570476177146',
    projectId: 'chat-app-last-try',
    storageBucket: 'chat-app-last-try.appspot.com',
  );
}
