// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjhTfErxSsSzMjJiUC9cd9HjZ7gaW-4Y',
    appId: '1:1079462628147:web:e4e8aec491e4f281e84c46',
    messagingSenderId: '1079462628147',
    projectId: 'flutter-tutorial-87767',
    authDomain: 'flutter-tutorial-87767.firebaseapp.com',
    storageBucket: 'flutter-tutorial-87767.appspot.com',
    measurementId: 'G-1JTW3ZQDT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXcVFDJm84wX5vOb3NEFsNj8-A7ylTz3I',
    appId: '1:1079462628147:android:5b54aa58dba1a6f2e84c46',
    messagingSenderId: '1079462628147',
    projectId: 'flutter-tutorial-87767',
    storageBucket: 'flutter-tutorial-87767.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmjhTfErxSsSzMjJiUC9cd9HjZ7gaW-4Y',
    appId: '1:1079462628147:web:709d07027e197b57e84c46',
    messagingSenderId: '1079462628147',
    projectId: 'flutter-tutorial-87767',
    authDomain: 'flutter-tutorial-87767.firebaseapp.com',
    storageBucket: 'flutter-tutorial-87767.appspot.com',
    measurementId: 'G-R9RXVPX1LR',
  );

}